name: MLflow CI Pipeline


on:

  push:

    branches:

      - main

      - master

  workflow_dispatch:


permissions:

  contents: write


jobs:

  training-job:

    name: Train Model with MLflow

    runs-on: ubuntu-latest


    steps:

      - name: Checkout Repository

        uses: actions/checkout@v4


      - name: Setup Miniconda

        uses: conda-incubator/setup-miniconda@v3

        with:

          auto-update-conda: true

          python-version: "3.10"


      - name: Install MLflow

        shell: bash -l {0}

        run: |

          pip install mlflow==2.19.0


      - name: Run MLProject

        shell: bash -l {0}

        run: |

          mlflow run ./MLProject --env-manager conda


      - name: Set up Git LFS

        run: |

          git config --global user.name "maisorpt"

          git config --global user.email "maisorpt@gmail.com"

          git lfs install

          git lfs track "mlruns/**"

          git add .gitattributes

          git commit -m "Track large files in mlruns with Git LFS" || true

          

      - name: Save mlruns to repo

        run: |

          git config --global user.name "maisorpt"

          git config --global user.email "maisorpt@gmail.com"

          

          git add -f mlruns/

          git commit -m "Save mlruns from CI run [skip ci]" || true

          git push origin main 
